//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class BRON_ORG_REF
    {
        public short BRON_ORG_ID { get; set; }
        public string BRON_ORG_NAME { get; set; }
        public Nullable<decimal> BRON_ORG_VID { get; set; }
        public string BRON_ORG_REM { get; set; }
    }
}
