//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class CHECK_MONTH_REF
    {
        public decimal CHECK_MONTH_ID { get; set; }
        public Nullable<decimal> ORD { get; set; }
        public string TITLE { get; set; }
        public string CUR { get; set; }
        public string HINT { get; set; }
    }
}
