//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ECOMPENS_REF
    {
        public short ECOMPENS_ID { get; set; }
        public string ECOMPENS_NAME { get; set; }
        public Nullable<decimal> ECOMPENS_VID { get; set; }
        public string ECOMPENS_REM { get; set; }
    }
}
