//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class EMOTOR_REF
    {
        public short EMOTOR_ID { get; set; }
        public string EMOTOR_NAME { get; set; }
        public Nullable<decimal> EMOTOR_VID { get; set; }
        public string EMOTOR_REM { get; set; }
    }
}
