//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ENERNAGR_REF
    {
        public short ENERNAGR_ID { get; set; }
        public string ENERNAGR_NAME { get; set; }
        public Nullable<decimal> ENERNAGR_VID { get; set; }
        public string ENERNAGR_REM { get; set; }
    }
}
