//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ENERPRI_REF
    {
        public short ENERPRI_ID { get; set; }
        public string ENERPRI_NAME { get; set; }
        public Nullable<decimal> ENERPRI_VID { get; set; }
        public string ENERPRI_REM { get; set; }
    }
}
