//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FACTORKZ_REF
    {
        public decimal FACTORKZ_ID { get; set; }
        public string POTR { get; set; }
        public Nullable<decimal> SHIFTCOD { get; set; }
        public Nullable<decimal> FKZ { get; set; }
        public Nullable<decimal> F2 { get; set; }
        public Nullable<decimal> F3 { get; set; }
    }
}
