//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MET_ISPOL_REF
    {
        public MET_ISPOL_REF()
        {
            this.METER_REF = new ObservableCollection<METER_REF>();
        }
    
        public short MET_ISPOL_ID { get; set; }
        public string MET_ISPOL_TYPE { get; set; }
    
        public virtual ObservableCollection<METER_REF> METER_REF { get; set; }
    }
}
