//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class NALOG_REF
    {
        public NALOG_REF()
        {
            this.NALOGZ_REF = new ObservableCollection<NALOGZ_REF>();
        }
    
        public short NALOG_ID { get; set; }
        public string NALOG { get; set; }
        public string NLG { get; set; }
    
        public virtual ObservableCollection<NALOGZ_REF> NALOGZ_REF { get; set; }
    }
}
