//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class NALOGZ_REF
    {
        public short NALOG_ID { get; set; }
        public System.DateTime DNAL { get; set; }
        public decimal ZNAL { get; set; }
    
        public virtual NALOG_REF NALOG_REF { get; set; }
    }
}
