//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class POWMAXZ_REF
    {
        public decimal POWMAX_ID { get; set; }
        public System.DateTime DATPOW { get; set; }
        public decimal COEFTAR { get; set; }
        public string REMPOW { get; set; }
    
        public virtual POWMAX_REF POWMAX_REF { get; set; }
    }
}
