//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PRECISE_REF
    {
        public PRECISE_REF()
        {
            this.METER_REF = new ObservableCollection<METER_REF>();
        }
    
        public decimal PRECISE_ID { get; set; }
        public string PRECISE_NAME { get; set; }
        public Nullable<decimal> PRECISE_VID { get; set; }
        public string PRECISE_REM { get; set; }
    
        public virtual ObservableCollection<METER_REF> METER_REF { get; set; }
    }
}
