//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class SETI_REF
    {
        public SETI_REF()
        {
            this.SETI_REF1 = new ObservableCollection<SETI_REF>();
        }
    
        public int SETI_ID { get; set; }
        public string SETI_NAME { get; set; }
        public Nullable<int> SETI_ID_PARENT { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> ATTR { get; set; }
        public Nullable<int> TYPS { get; set; }
        public string CONTACT { get; set; }
        public string WWW { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string MAIL { get; set; }
        public string ADR { get; set; }
        public string NIFS { get; set; }
        public string SETI_NAMES { get; set; }
        public string REMA { get; set; }
    
        public virtual ObservableCollection<SETI_REF> SETI_REF1 { get; set; }
        public virtual SETI_REF SETI_REF2 { get; set; }
    }
}
