//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TARPOPUL_REF
    {
        public short TARPOPUL_ID { get; set; }
        public string TARPOPUL_N { get; set; }
        public string TARPOPUL_NA { get; set; }
    }
}
