//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TRANSFPOWER
    {
        public int TRANS_ID { get; set; }
        public int POWER { get; set; }
        public decimal HV { get; set; }
        public decimal MV { get; set; }
        public decimal LV { get; set; }
        public decimal PX { get; set; }
        public decimal PK { get; set; }
        public string TYPE_TRANS { get; set; }
    }
}
