//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TYPEHOUR_REF
    {
        public decimal TYPEHOUR_ID { get; set; }
        public string NAIM { get; set; }
        public string CHOUR { get; set; }
    }
}
