//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WIRE_REF
    {
        public WIRE_REF()
        {
            this.WIREZ_REF = new ObservableCollection<WIREZ_REF>();
        }
    
        public string MAT { get; set; }
        public string MATTER { get; set; }
    
        public virtual ObservableCollection<WIREZ_REF> WIREZ_REF { get; set; }
    }
}
