//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefData
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class WIREZ_REF
    {
        public string MAT { get; set; }
        public string MARK { get; set; }
        public short AREA { get; set; }
        public decimal RESIST { get; set; }
    
        public virtual WIRE_REF WIRE_REF { get; set; }
    }
}
